global:
  scrape_interval: 15s  # Tiempo entre cada recolección de métricas

scrape_configs:
  - job_name: 'weather-exporter'
    static_configs:
      - targets: ['exporter:8000']  # Cambié 'localhost' por 'exporter' para usar el nombre del contenedor en Docker

